export class App {}
export class Notice {}
export class Plugin {}
export class PluginSettingTab {}
export class Setting {}
export class TFile {}
export class Vault {}
export class WorkspaceLeaf {}
export class ItemView {}
export class MarkdownView {}
