"""Markdown report generation for the conformance suite.

The ``ConformanceReporter`` is a pytest plugin that collects test outcomes
and renders a human-readable Markdown report suitable for embedding in
operator documentation or committing alongside a release.
"""

from __future__ import annotations

import datetime
from typing import Any

import pytest


class ConformanceReporter:
    """Pytest plugin that records outcomes and generates a Markdown report."""

    def __init__(self, backend: str = "sqlite") -> None:
        self.backend = backend
        self._results: list[dict[str, Any]] = []
        self._started_at = datetime.datetime.now(datetime.UTC)

    # ------------------------------------------------------------------
    # pytest hooks
    # ------------------------------------------------------------------

    def pytest_runtest_logreport(self, report: pytest.TestReport) -> None:
        if report.when != "call":
            return
        self._results.append(
            {
                "nodeid": report.nodeid,
                "outcome": report.outcome,  # "passed" | "failed" | "skipped"
                "longrepr": str(report.longrepr) if report.longrepr else "",
            }
        )

    # ------------------------------------------------------------------
    # Report rendering
    # ------------------------------------------------------------------

    def generate_markdown(self) -> str:
        elapsed = datetime.datetime.now(datetime.UTC) - self._started_at
        counts = _outcome_counts(self._results)
        lines = _summary_lines(self.backend, self._started_at, elapsed, counts)
        lines.extend(_failure_lines(self._results))
        lines.extend(_skipped_lines(self._results))
        lines.extend(_detail_lines(self._results))
        lines.append("")
        lines.append(
            "_Generated by [stigmem-conformance](https://docs.stigmem.dev/guides/conformance)_"
        )
        return "\n".join(lines)


def _outcome_counts(results: list[dict[str, Any]]) -> dict[str, int]:
    return {
        "total": len(results),
        "passed": sum(1 for r in results if r["outcome"] == "passed"),
        "failed": sum(1 for r in results if r["outcome"] == "failed"),
        "skipped": sum(1 for r in results if r["outcome"] == "skipped"),
    }


def _summary_lines(
    backend: str,
    started_at: datetime.datetime,
    elapsed: datetime.timedelta,
    counts: dict[str, int],
) -> list[str]:
    status_emoji = "✅" if counts["failed"] == 0 else "❌"
    return [
        f"# Stigmem Conformance Report — `{backend}` backend",
        "",
        f"**Generated:** {started_at.strftime('%Y-%m-%d %H:%M UTC')}  ",
        f"**Duration:** {elapsed.total_seconds():.1f}s  ",
        "**Result:** "
        f"{status_emoji} {counts['passed']}/{counts['total']} passed, "
        f"{counts['failed']} failed, {counts['skipped']} skipped",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Passed | {counts['passed']} |",
        f"| Failed | {counts['failed']} |",
        f"| Skipped | {counts['skipped']} |",
        f"| **Total** | **{counts['total']}** |",
        "",
    ]


def _failure_lines(results: list[dict[str, Any]]) -> list[str]:
    failed = [r for r in results if r["outcome"] == "failed"]
    if not failed:
        return []

    lines = ["## Failures", ""]
    for result in failed:
        lines.extend([
            f"### `{result['nodeid']}`",
            "",
            "```",
            result["longrepr"][:2000],
            "```",
            "",
        ])
    return lines


def _skipped_lines(results: list[dict[str, Any]]) -> list[str]:
    skipped = [r for r in results if r["outcome"] == "skipped"]
    if not skipped:
        return []

    lines = ["## Skipped", ""]
    for result in skipped:
        reason = result["longrepr"].split("Skipped: ")[-1].strip() if result["longrepr"] else ""
        lines.append(f"- `{result['nodeid']}`" + (f" — {reason}" if reason else ""))
    lines.append("")
    return lines


def _detail_lines(results: list[dict[str, Any]]) -> list[str]:
    lines = [
        "## Test details",
        "",
        "| Test | Outcome |",
        "|------|---------|",
    ]
    icons = {"passed": "✅", "failed": "❌", "skipped": "⏭"}
    for result in results:
        icon = icons.get(result["outcome"], "?")
        short = result["nodeid"].split("::")[-1]
        lines.append(f"| `{short}` | {icon} {result['outcome']} |")
    return lines
