"""Markdown report generation for the conformance suite.

The ``ConformanceReporter`` is a pytest plugin that collects test outcomes
and renders a human-readable Markdown report suitable for embedding in
operator documentation or committing alongside a release.
"""

from __future__ import annotations

import datetime
from typing import Any

import pytest


class ConformanceReporter:
    """Pytest plugin that records outcomes and generates a Markdown report."""

    def __init__(self, backend: str = "sqlite") -> None:
        self.backend = backend
        self._results: list[dict[str, Any]] = []
        self._started_at = datetime.datetime.now(datetime.UTC)

    # ------------------------------------------------------------------
    # pytest hooks
    # ------------------------------------------------------------------

    def pytest_runtest_logreport(self, report: pytest.TestReport) -> None:
        if report.when != "call":
            return
        self._results.append(
            {
                "nodeid": report.nodeid,
                "outcome": report.outcome,  # "passed" | "failed" | "skipped"
                "longrepr": str(report.longrepr) if report.longrepr else "",
            }
        )

    # ------------------------------------------------------------------
    # Report rendering
    # ------------------------------------------------------------------

    def generate_markdown(self) -> str:
        elapsed = datetime.datetime.now(datetime.UTC) - self._started_at
        total = len(self._results)
        passed = sum(1 for r in self._results if r["outcome"] == "passed")
        failed = sum(1 for r in self._results if r["outcome"] == "failed")
        skipped = sum(1 for r in self._results if r["outcome"] == "skipped")

        status_emoji = "✅" if failed == 0 else "❌"
        lines = [
            f"# Stigmem Conformance Report — `{self.backend}` backend",
            "",
            f"**Generated:** {self._started_at.strftime('%Y-%m-%d %H:%M UTC')}  ",
            f"**Duration:** {elapsed.total_seconds():.1f}s  ",
            f"**Result:** {status_emoji} {passed}/{total} passed, {failed} failed, {skipped} skipped",
            "",
            "## Summary",
            "",
            f"| Metric | Count |",
            f"|--------|-------|",
            f"| Passed | {passed} |",
            f"| Failed | {failed} |",
            f"| Skipped | {skipped} |",
            f"| **Total** | **{total}** |",
            "",
        ]

        if failed:
            lines += [
                "## Failures",
                "",
            ]
            for r in self._results:
                if r["outcome"] == "failed":
                    lines.append(f"### `{r['nodeid']}`")
                    lines.append("")
                    lines.append("```")
                    lines.append(r["longrepr"][:2000])
                    lines.append("```")
                    lines.append("")

        if skipped:
            lines += [
                "## Skipped",
                "",
            ]
            for r in self._results:
                if r["outcome"] == "skipped":
                    reason = r["longrepr"].split("Skipped: ")[-1].strip() if r["longrepr"] else ""
                    lines.append(f"- `{r['nodeid']}`" + (f" — {reason}" if reason else ""))
            lines.append("")

        lines += [
            "## Test details",
            "",
            "| Test | Outcome |",
            "|------|---------|",
        ]
        for r in self._results:
            icon = {"passed": "✅", "failed": "❌", "skipped": "⏭"}.get(r["outcome"], "?")
            short = r["nodeid"].split("::")[-1]
            lines.append(f"| `{short}` | {icon} {r['outcome']} |")

        lines.append("")
        lines.append(
            "_Generated by [stigmem-conformance](https://docs.stigmem.dev/guides/conformance)_"
        )
        return "\n".join(lines)
