#!/usr/bin/env python3
"""Normalize the generated TypeScript SDK header."""

from __future__ import annotations

import argparse
from pathlib import Path

HEADER = """\
/**
 * AUTO-GENERATED by openapi-typescript.
 * Do not make direct changes to the file.
 */

"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=Path)
    args = parser.parse_args()

    text = args.path.read_text(encoding="utf-8")
    if text.startswith("/**"):
        end = text.find("*/")
        if end != -1:
            text = text[end + 2 :].lstrip("\n")
    args.path.write_text(HEADER + text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
