#!/usr/bin/env bash
# stigmem-snapshot.sh — daily snapshot of Stigmem facts and contradictions to a markdown backup.
#
# Useful as a cron-driven backup of stigmem state for operators who want a
# human-readable, version-controllable record alongside their primary database.
# The output groups facts by entity for readability and includes a contradiction-
# metrics table at the end.
#
# Usage:
#     stigmem-snapshot.sh \
#         --scope <local|team|company|public> \
#         --entities "<uri>[,<uri>...]" \
#         --output <file-path> \
#         [--limit 200] \
#         [--no-contradictions] \
#         [--api-key <key>] \
#         [--node-url <url>]
#
# Required:
#     --scope          Stigmem scope to snapshot (local, team, company, public).
#     --entities       Comma-separated list of entity URIs to snapshot (e.g.,
#                      "team:ops,agent:bot-1"). Each is fetched separately and
#                      rendered as its own section in the output.
#     --output         Destination markdown file path.
#
# Optional:
#     --limit          Max facts per fetch (default: 200). Pagination is not
#                      currently handled; if the deployment exceeds this, raise
#                      the limit or run separate snapshots per entity.
#     --no-contradictions
#                      Skip the contradiction-metrics section.
#     --api-key        Bearer token for the stigmem API. Defaults to
#                      $STIGMEM_API_KEY env var. Omit if the node is
#                      unauthenticated (dev only).
#     --node-url       Stigmem node base URL. Defaults to $STIGMEM_URL env var,
#                      or http://localhost:8765 if neither is set.
#
# Example (cron):
#     # Daily 06:00 UTC snapshot of the team scope to /var/backups/stigmem/
#     0 6 * * * /usr/local/bin/stigmem-snapshot.sh \
#                  --scope team \
#                  --entities "team:ops,team:eng" \
#                  --output /var/backups/stigmem/snapshot-$(date -u +%Y-%m-%d).md \
#                  --api-key $STIGMEM_API_KEY
#
# Exit codes:
#     0   Snapshot written successfully (with or without contradictions).
#     1   Argument error or failure writing output.
#
# Dependencies: bash 4+, curl, jq.

set -euo pipefail

# -------- defaults --------
STIGMEM_URL_DEFAULT="${STIGMEM_URL:-http://localhost:8765}"
LIMIT_DEFAULT=200

# -------- argument parsing --------
SCOPE=""
ENTITIES=""
OUTPUT=""
LIMIT="${LIMIT_DEFAULT}"
INCLUDE_CONTRADICTIONS=1
API_KEY="${STIGMEM_API_KEY:-}"
NODE_URL="${STIGMEM_URL_DEFAULT}"

usage() {
  sed -n '2,/^# Dependencies/p' "$0" | sed 's/^# \?//'
  exit "${1:-2}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --scope)            SCOPE="$2"; shift 2 ;;
    --entities)         ENTITIES="$2"; shift 2 ;;
    --output)           OUTPUT="$2"; shift 2 ;;
    --limit)            LIMIT="$2"; shift 2 ;;
    --no-contradictions) INCLUDE_CONTRADICTIONS=0; shift ;;
    --api-key)          API_KEY="$2"; shift 2 ;;
    --node-url)         NODE_URL="$2"; shift 2 ;;
    -h|--help)          usage 0 ;;
    *) echo "Unknown argument: $1" >&2; usage 2 ;;
  esac
done

# -------- validation --------
if [[ -z "${SCOPE}" || -z "${ENTITIES}" || -z "${OUTPUT}" ]]; then
  echo "Error: --scope, --entities, and --output are required." >&2
  usage 2
fi

case "${SCOPE}" in
  local|team|company|public) ;;
  *) echo "Error: --scope must be one of local, team, company, public." >&2; exit 2 ;;
esac

if ! [[ "${LIMIT}" =~ ^[0-9]+$ ]]; then
  echo "Error: --limit must be a positive integer." >&2
  exit 2
fi

# -------- helpers --------
AUTH_HEADER=()
if [[ -n "${API_KEY}" ]]; then
  AUTH_HEADER=(-H "Authorization: Bearer ${API_KEY}")
fi

fetch_facts() {
  local entity="$1"
  curl -sf "${AUTH_HEADER[@]+${AUTH_HEADER[@]}}" \
    "${NODE_URL%/}/v1/facts?entity=${entity}&scope=${SCOPE}&limit=${LIMIT}&include_contradicted=false&include_expired=false"
}

fetch_conflicts() {
  local status="$1"
  curl -sf "${AUTH_HEADER[@]+${AUTH_HEADER[@]}}" \
    "${NODE_URL%/}/v1/conflicts?status=${status}&limit=500"
}

# -------- pre-fetch contradictions (also used to detect has_more) --------
UNRESOLVED_JSON='{"conflicts":[],"has_more":false}'
RESOLVED_JSON='{"conflicts":[],"has_more":false}'

if [[ "${INCLUDE_CONTRADICTIONS}" == "1" ]]; then
  UNRESOLVED_JSON="$(fetch_conflicts "unresolved" 2>/dev/null || echo "${UNRESOLVED_JSON}")"
  RESOLVED_JSON="$(fetch_conflicts "resolved" 2>/dev/null || echo "${RESOLVED_JSON}")"
fi

# -------- write output --------
TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
mkdir -p "$(dirname -- "${OUTPUT}")"

{
  echo "# Stigmem Snapshot — ${TIMESTAMP}"
  echo ""
  echo "Auto-generated by \`stigmem-snapshot.sh\`. Do not edit manually."
  echo ""
  echo "- **Node:** ${NODE_URL}"
  echo "- **Scope:** ${SCOPE}"
  echo "- **Entities:** ${ENTITIES}"
  echo ""

  IFS=',' read -ra ENTITY_LIST <<< "${ENTITIES}"
  for entity in "${ENTITY_LIST[@]}"; do
    entity="$(echo "${entity}" | xargs)"  # trim whitespace
    [[ -z "${entity}" ]] && continue
    echo "## ${entity} — ${SCOPE} scope"
    echo ""
    fetch_facts "${entity}" \
      | jq -r '.facts[] | "- **\(.relation)** (source=\(.source), conf=\(.confidence)): \(.value.v // .value.type)"' \
      2>/dev/null || echo "_No facts found or stigmem unreachable._"
    echo ""
  done

  if [[ "${INCLUDE_CONTRADICTIONS}" == "1" ]]; then
    echo "## Contradiction Metrics"
    echo ""
    jq -rn \
      --argjson u "${UNRESOLVED_JSON}" \
      --argjson r "${RESOLVED_JSON}" \
      '
        ($u.conflicts + $r.conflicts) as $all |
        if ($all | length) == 0 then
          "_No contradictions detected._"
        else
          (
            "| Scope | Unresolved | Resolved | Total |",
            "|-------|------------|----------|-------|",
            (
              $all
              | group_by((.fact_a?.scope // .fact_b?.scope // "unknown"))[]
              | {
                  scope:      (.[0].fact_a?.scope // .[0].fact_b?.scope // "unknown"),
                  unresolved: (map(select(.status == "unresolved")) | length),
                  resolved:   (map(select(.status == "resolved"))   | length),
                  total:      length
                }
              | "| \(.scope) | \(.unresolved) | \(.resolved) | \(.total) |"
            )
          )
        end
      ' 2>/dev/null || echo "_Error fetching contradiction data._"

    if [[ "$(echo "${UNRESOLVED_JSON}" | jq -r '.has_more // false')" == "true" ]] || \
       [[ "$(echo "${RESOLVED_JSON}"   | jq -r '.has_more // false')" == "true" ]]; then
      echo ""
      echo "> **Note:** conflict list exceeded 500 entries; counts shown are a lower bound."
    fi
    echo ""
  fi
} > "${OUTPUT}"

echo "Snapshot written to ${OUTPUT}"
