#!/usr/bin/env bash
# Daily snapshot: dumps current Stigmem state for company:acme to a markdown backup.
# Usage: snapshot.sh <memory-dir>
# Example (cron): 0 6 * * * /path/to/snapshot.sh /path/to/memory
set -euo pipefail

STIGMEM_URL="${STIGMEM_URL:-http://localhost:8765}"
MEMORY_DIR="${1:?Usage: snapshot.sh <memory-dir>}"

OUTFILE="${MEMORY_DIR}/stigmem-snapshot.md"
TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

AUTH_HEADER=()
if [[ -n "${STIGMEM_API_KEY:-}" ]]; then
  AUTH_HEADER=(-H "Authorization: Bearer ${STIGMEM_API_KEY}")
fi

fetch_facts() {
  local entity="$1"
  local scope="$2"
  curl -sf "${AUTH_HEADER[@]+${AUTH_HEADER[@]}}" \
    "${STIGMEM_URL}/v1/facts?entity=${entity}&scope=${scope}&limit=200&include_contradicted=false&include_expired=false"
}

{
  echo "# Stigmem Snapshot — ${TIMESTAMP}"
  echo ""
  echo "Auto-generated by \`stigmem/dogfood/snapshot.sh\`. Do not edit manually."
  echo ""

  echo "## company:acme — company scope"
  echo ""
  fetch_facts "company:acme" "company" \
    | jq -r '.facts[] | "- **\(.relation)** (\(.source), conf=\(.confidence)): \(.value.v // .value.type)"' \
    2>/dev/null || echo "_No facts found or Stigmem unreachable._"
  echo ""

  echo "## agent:ceo — company scope"
  echo ""
  fetch_facts "agent:ceo" "company" \
    | jq -r '.facts[] | "- **\(.relation)** (\(.source), conf=\(.confidence)): \(.value.v // .value.type)"' \
    2>/dev/null || echo "_No facts found._"
  echo ""
} > "${OUTFILE}"

echo "Snapshot written to ${OUTFILE}"
